- doc/reporter-ureport.txt
- src/include/internal_libreport.h
- src/include/libreport_types.h
- src/include/ureport.h
- src/lib/abrt_types.c
- src/lib/configuration_files.c
- src/lib/ureport.c
- src/plugins/reporter-ureport.c
- src/plugins/ureport.conf
- tests/Makefile.am
- tests/ureport-rhts-credentials/rhtsupport.conf
- tests/ureport.at
This pull request includes commits required for https://bugzilla.redhat.com/show_bug.cgi?id=1174833
> RHEL7: HTTP Basic Access Authentication for uReport

- configure.ac
- libreport.spec.in
- po/POTFILES.in
- src/include/Makefile.am
- src/include/internal_libreport.h
- src/include/reporters.h
- src/lib/Makefile.am
- src/lib/reporters.c
- src/lib/strbuf.c
- src/plugins/Makefile.am
- src/plugins/mantisbt.c
- src/plugins/mantisbt.conf
- src/plugins/mantisbt.h
- src/plugins/mantisbt_format.conf
- src/plugins/mantisbt_formatdup.conf
- src/plugins/reporter-mantisbt.c
- src/plugins/rhbz.c
- src/plugins/rhbz.h
> reporter mantisbt

- src/plugins/reporter-mantisbt.c
> Fixed typos

- configure.ac
- libreport.spec.in
- src/include/dump_dir.h
- src/include/internal_libreport.h
- src/include/problem_data.h
- src/lib/Makefile.am
- src/lib/compress.c
- src/lib/create_dump_dir.c
- src/lib/dump_dir.c
- src/lib/get_cmdline.c
- src/lib/make_descr.c
- src/lib/read_write.c
- src/lib/report_event.conf
- src/plugins/report_uReport.xml.in
- src/plugins/reporter-bugzilla.c
- src/workflows/report_fedora.conf
- src/workflows/report_logger.conf
- src/workflows/report_mailx.conf
- src/workflows/report_rhel.conf
- src/workflows/report_rhel_bugzilla.conf
- src/workflows/report_uploader.conf
See https://github.com/abrt/abrt/issues/548 for more details.
> Changes needed for systemd-coredumpctl

- src/plugins/mantisbt.c
- src/plugins/mantisbt.h
- src/plugins/reporter-mantisbt.c
Project and custom fields are addressed by id, so we need to get their ids from names.
Used SOAP API methods:
mc_project_get_id_from_name
mc_project_get_custom_fields
> Added 'get ids from names' functionality

- libreport.spec.in
- src/plugins/Makefile.am
- src/plugins/centos_report_event.conf
- src/plugins/report_CentOSBugTracker.conf
- src/plugins/report_CentOSBugTracker.xml.in
- src/workflows/Makefile.am
- src/workflows/report_centos.conf
- src/workflows/workflow_CentOSCCpp.xml.in
- src/workflows/workflow_CentOSJava.xml.in
- src/workflows/workflow_CentOSKerneloops.xml.in
- src/workflows/workflow_CentOSLibreport.xml.in
- src/workflows/workflow_CentOSPython.xml.in
- src/workflows/workflow_CentOSPython3.xml.in
- src/workflows/workflow_CentOSVmcore.xml.in
- src/workflows/workflow_CentOSXorg.xml.in
added workflow for CentOS and definition of the report_CentOSBugTracker event
Fixes #304
> Centos workflow

- src/plugins/mantisbt.c
- src/plugins/mantisbt.h
- src/plugins/reporter-mantisbt.c
Updated searching methods to work with latest update of MantisBT SOAP API.
> reporter-mantisbt: update searching methods

- src/plugins/mantisbt.c
If there are two custom fields, the added property looks like follows:
"ns3:arrayType="ns2:CustomFieldValueForIssueData[2]"
> reporter-mantisbt: add property (array size) to the <custom_fields> item

- libreport.spec.in
- src/client-python/reportclient/Makefile.am
- src/client-python/reportclient/__init__.py
- src/client-python/reportclient/clientmodule.c
- src/client-python/reportclient/yumdebuginfo.py
Related to #172, rhbz#1014684.
Signed-off-by: Martin Milata <mmilata@redhat.com>
> Port reportclient to python3

- po/POTFILES.in
> add workflow_CentOS* and report_CentOSBugTracker.xml.in to POTFILES.in

- src/plugins/centos_report_event.conf
- src/workflows/report_centos.conf
> switch from 'analyzer' to 'type'

- src/client-python/reportclient/debuginfo.py
Related to rhbz#1169774 rhbz#1213485 rhbz#1036918
> report client: provide cpio log when unpacking fails

- src/client-python/reportclient/client.c
- src/client-python/reportclient/clientmodule.c
- src/client-python/reportclient/common.h
- src/gui-wizard-gtk/wizard.c
- src/include/client.h
- src/include/run_event.h
- src/lib/client.c
- src/lib/run_event.c
This function allows to save result to the conf file and return it in next time when the ask function is called.
Related to rhbz#986876
Related to abrt/gnome-abrt#131
> add ask_yes_no_save_result

- libreport.spec.in
Signed-off-by: Richard Marko <rmarko@fedoraproject.org>
> spec: use more appropriate url

- src/client-python/reportclient/__init__.py
- src/client-python/reportclient/debuginfo.py
- src/client-python/reportclient/dnfdebuginfo.py
- src/client-python/reportclient/yumdebuginfo.py
- src/lib/configuration_files.c
> Minor fixes

- src/include/dump_dir.h
- src/include/internal_libreport.h
- src/lib/dump_dir.c
- src/plugins/bugzilla_format.conf
- src/plugins/bugzilla_format_anaconda.conf
- src/plugins/bugzilla_format_analyzer_libreport.conf
- src/plugins/bugzilla_formatdup.conf
- src/plugins/bugzilla_formatdup_anaconda.conf
- src/plugins/mantisbt_format.conf
- src/plugins/mantisbt_format_analyzer_libreport.conf
- src/plugins/mantisbt_formatdup.conf
- src/plugins/mantisbt_formatdup_analyzer_libreport.conf
- tests/dump_dir.at
Do not include it in bug reports.
> support new dump dir element 'tid'

- src/include/internal_libreport.h
- src/include/problem_data.h
- src/include/run_event.h
- src/lib/glib_support.c
- src/lib/make_descr.c
- src/lib/problem_data.c
- src/lib/run_event.c
- tests/glib_helpers.at
https://bugzilla.redhat.com/show_bug.cgi?id=1224984
>   RHEL7: changes needed for 'abrt-cli over D-Bus'

- src/include/internal_libreport.h
- src/include/run_event.h
- src/lib/glib_support.c
- src/lib/run_event.c
- tests/glib_helpers.at
A step towards our ultimate goal "no file system access".
> Get the possible events list for a problem data

- src/lib/dump_dir.c
The current implementation uses the flag only to ignore *unlocked or
broken* problems that misses some of the required files. If the dump
directory is locked by an existing process, dd_lock() waits until the
process unlocks it and that causes problems in UI.
Example:
1. abrt-hook-ccpp creates a new dump directory and goes to generate
core_backtrace, which blocks it for several seconds.
2. An user wants to get list of all problems from abrt-dbus.
3. abrt-dbus got stucked on the new problem locked by abrt-hook-ccpp.
4. D-Bus connection time-outs, abrt-dbus becomes unreachable.
This patch adds a new condition which breaks the loop wait for lock if
the problem directory is locked by existing process. All other cases
are already handled and dd_lock() either returns an error or steals the
lock …
> dd: extend the scope of DD_DONT_WAIT_FOR_LOCK

- src/plugins/rhbz.c
Parse /etc/os-release ('os-info' element), read VARIANT_ID and put its
value to Whiteboard of the newly created bug.
This commit allows users to search for ";VARIANT_ID=$ID;".
Related to abrt/abrt#995
> bugzilla: put VARIANT_ID= to Whiteboard

- src/plugins/bugzilla_format.conf
- src/plugins/mantisbt_format.conf
> bugzilla: don't attach build_ids

- src/lib/report_event.conf
> events: improve example

- doc/report_Bugzilla.conf.txt
- doc/reporter-bugzilla.txt
- src/plugins/reporter-bugzilla.c
- src/plugins/rhbz.c
- src/plugins/rhbz.h
Test case commit: https://github.com/abrt/abrt/commit/1feaa22cf2fadde5a7ff313fcc53f2355dfdc438
> Bugzilla: private duplicate reports

- src/include/internal_libreport.h
- src/lib/dump_dir.c
- tests/dump_dir.at
> dd: make function uid_in_group() public

- src/plugins/bugzilla_formatdup.conf
- src/plugins/bugzilla_formatdup_anaconda.conf
- src/plugins/mantisbt_formatdup.conf
- src/plugins/mantisbt_formatdup_analyzer_libreport.conf
Fixes Red Hat Bugzilla Bug 1072874
Signed-off-by: Jan Beran <jberan@redhat.com>
> formatdup: more universal comment

- src/include/internal_libreport.h
- src/lib/dump_dir.c
- tests/dump_dir.at
> RHEL6: dd: make function uid_in_group() public

- doc/reporter-rhtsupport.txt
- src/plugins/reporter-rhtsupport.c
Related to: rhbz#1261398
Related testcase: https://github.com/abrt/abrt/pull/1106
> rhtsupport: use problme report API to create description

- src/plugins/report_CentOSBugTracker.xml.in
- src/plugins/reporter-ureport.c
Thanks for fixing these typos.
> Fix minor typos

- src/client-python/reportclient/debuginfo.py
> report client: add silent mode to clean_up()

- Makefile.am
> makefile: define LANG in release target

- doc/Makefile.am
- doc/report_event.conf.txt
- doc/report_uReport.conf.txt
- libreport.spec.in
- po/POTFILES.in
- src/gui-wizard-gtk/wizard.c
- src/gui-wizard-gtk/wizard.glade
- src/include/event_config.h
- src/include/internal_libreport.h
- src/include/problem_data.h
- src/lib/event_xml_parser.c
- src/lib/problem_data.c
- src/plugins/report_RHTSupport.xml.in
- src/plugins/report_uReport.xml.in
- src/plugins/reporter-rhtsupport.c
- src/workflows/Makefile.am
- src/workflows/report_uReport.conf
- src/workflows/workflow_RHELCCpp.xml.in
- src/workflows/workflow_RHELJava.xml.in
- src/workflows/workflow_RHELKerneloops.xml.in
- src/workflows/workflow_RHELLibreport.xml.in
- src/workflows/workflow_RHELPython.xml.in
- src/workflows/workflow_RHELvmcore.xml.in
- src/workflows/workflow_RHELxorg.xml.in
- src/workflows/workflow_uReport.xml.in
- tests/helpers/testsuite.h
- tests/problem_data.at
> Refined workflow for reporting to RHEL

- src/include/internal_libreport.h
- src/include/workflow.h
- src/lib/workflow.c
- document what needs to be documented
- publish functions necessary to get all configured workflows
- get rid of the need to know the default path to directory with workflows
> Workflow usability fixes

- src/include/internal_libreport.h
- src/lib/dump_dir.c
- tests/dump_dir.at
Related to rhbz#1277849 rhbz#1277848
> RHEL7: make function uid_in_group() public

- doc/Makefile.am
- doc/report_Uploader.conf.txt
- doc/reporter-upload.txt
- doc/upload.conf.txt
- libreport.spec.in
- src/include/libreport_curl.h
- src/lib/curl.c
- src/plugins/Makefile.am
- src/plugins/report_Uploader.conf
- src/plugins/report_Uploader.xml.in
- src/plugins/reporter-upload.c
- src/plugins/upload.conf
> RHEL7: Configurable SSH Key File For ABRT's reportuploader 

- doc/Makefile.am
- doc/report_uReport.conf.txt
- libreport.spec.in
- po/POTFILES.in
- src/gui-wizard-gtk/wizard.c
- src/gui-wizard-gtk/wizard.glade
- src/include/event_config.h
- src/include/internal_libreport.h
- src/include/problem_data.h
- src/lib/event_xml_parser.c
- src/lib/problem_data.c
- src/plugins/report_RHTSupport.xml.in
- src/plugins/report_uReport.xml.in
- src/plugins/reporter-rhtsupport.c
- src/workflows/Makefile.am
- src/workflows/report_uReport.conf
- src/workflows/workflow_RHELCCpp.xml.in
- src/workflows/workflow_RHELJava.xml.in
- src/workflows/workflow_RHELKerneloops.xml.in
- src/workflows/workflow_RHELLibreport.xml.in
- src/workflows/workflow_RHELPython.xml.in
- src/workflows/workflow_RHELvmcore.xml.in
- src/workflows/workflow_RHELxorg.xml.in
- src/workflows/workflow_uReport.xml.in
- tests/problem_data.at
Do not open customers cases even if they do not require Red Hat Support to work on their cases.
Related to rhbz#1258482
> RHEL7: Refined workflow

- augeas/libreport.aug
- augeas/test_libreport.aug
> augeas: trim spaces before key value

- augeas/libreport.aug
- augeas/test_libreport.aug
> RHEL7: augeas: trim spaces before key value

- src/gui-wizard-gtk/ignored_words.conf
Related to rhbz#1319779
Related to rhbz#1311663
> Reduce false positive cases in ignored_words.conf

- doc/reporter-mailx.txt
- src/include/internal_libreport.h
- src/lib/make_descr.c
- src/plugins/reporter-mailx.c
> RHEL7: use problem report api to define an emais' content

- src/gui-wizard-gtk/wizard.c
> wizard: do not create reproducible if complex_detail == no

- README
> doc: make README more verbose

- doc/reporter-mailx.txt
> man: fix formating

- src/workflows/workflow_FedoraCCpp.xml.in
- src/workflows/workflow_FedoraJava.xml.in
- src/workflows/workflow_FedoraJavaScript.xml.in
- src/workflows/workflow_FedoraKerneloops.xml.in
- src/workflows/workflow_FedoraLibreport.xml.in
- src/workflows/workflow_FedoraPython.xml.in
- src/workflows/workflow_FedoraPython3.xml.in
- src/workflows/workflow_FedoraVmcore.xml.in
- src/workflows/workflow_FedoraXorg.xml.in
> workflows: run analyze_BodhiUpdates event on Fedora

- doc/reporter-systemd-journal.txt
- src/plugins/reporter-systemd-journal.c
- src/report-python/__init__.py
> reporter-systemd-journal improvements

- CHANGELOG.md
- src/include/internal_libreport.h
- src/lib/get_cmdline.c
- tests/helpers/testsuite.h
- tests/helpers/testsuite_tools.h
- tests/proc_helpers.at
This pull request is necessary for the future enhancements of ABRT.
> Several bug fixes and improvements when dealing with containers

- Makefile.am
> Fixing issue with README.md

- src/gtk-helpers/event_config_dialog.c
- src/gtk-helpers/problem_details_widget.c
- src/gui-wizard-gtk/wizard.c
> gui: replace deprecated gtk3 functions

- src/include/dump_dir.h
- src/lib/create_dump_dir.c
> dd: extend create_dump_dir to allow set pid in dumpdir name

- src/include/internal_libreport.h
- tests/proc_helpers.at
> lib: Introduce pid_for_children element from ns

- src/gui-wizard-gtk/ignored_words.conf
> ignored words: add SYSTEMD_NSS_BYPASS_BUS

- augeas/libreport.aug
- doc/reporter-bugzilla.txt
- doc/reporter-mantisbt.txt
- doc/reporter-rhtsupport.txt
- doc/reporter-ureport.txt
- src/include/internal_libreport.h
- src/lib/ureport.c
- src/plugins/bugzilla.conf
- src/plugins/centos_report_event.conf
- src/plugins/mantisbt.conf
- src/plugins/report.c
- src/plugins/reporter-bugzilla.c
- src/plugins/reporter-mantisbt.c
- src/plugins/reporter-rhtsupport.c
- src/plugins/rhtsupport.conf
related to bugzillas:
https://bugzilla.redhat.com/show_bug.cgi?id=1008994
https://bugzilla.redhat.com/show_bug.cgi?id=1008977
> Fix 1008994 2

- libreport.spec.in
> Various cleanup and improvements to spec file

- libreport.spec.in
- src/report-python/Makefile.am
- src/report-python/__init__.py
> Conditionalize the Python2 and Python3 

- libreport.spec.in
- src/gui-wizard-gtk/wizard.c
- src/gui-wizard-gtk/wizard.glade
The fros package is broken and hasn't been maintained for quite some time.
closes #104
> Remove option to screencast problems

- libreport.spec.in
> spec: Make libreport-filesystem subpackage noarch

- src/client-python/reportclient/debuginfo.py
This commit picks a piece of code responsible for looking up debuginfo
packages into own method. For making sure that it works in any code that
used it the old way, it checks if the method for finding packages was
already called and if not, calls it directly.
Purpose of this change is to be able to get size of packages those are
going to be installed before installing them. In that case anyone using
these downloader classes is going to be able for example prepare enough
space for the newly installed packages.
Related to #811978.
> report-client: Find debuginfos in own method

- src/lib/get_cmdline.c
> lib: Seek beginning of mountinfo file

- tests/reported_to.at
> testsuite: Correct string format

- src/plugins/reporter-bugzilla.c
> reporer-bugzilla: Check if product version available

- HACKING.md
> Add HACKING.md

- src/lib/dump_dir.c
The dump_dir instance is leaked if the deletion fails.
Resolves rhbz#1671233
> lib: dump_dir: Clean up on failure in dd_delete()

- src/lib/problem_report.c
> Check for empty fmt_file name when printing error msgs

- configure.ac
- libreport.spec.in
- src/client-python/reportclient/Makefile.am
- src/report-python/report/Makefile.am
- tests/Makefile.am
- tests/local.at
> Remove Python 2 support

- src/include/internal_libreport.h
- tests/proc_helpers.at
Linux 5.6 introduces a new time namespace:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=769071ac9f20b6a447410c7eaa55d1a5233ef40c
> Support new kernel namespace

- zanata.xml
> Remove unused zanata.xml

- src/client-python/reportclient/debuginfo.py
This is called by abrt-action-install-debuginfo-to-abrt-cache which used to be setuid and now is setgid binary.
Therefore we do not need to setuid and we neither need it.
> setgid instead of setuid the abrt-action-install-debuginfo-to-abrt-cache [RHBZ 1796245]

- src/cli/run-command.c
- src/client-python/reportclient/clientmodule.c
- src/gui-wizard-gtk/main.c
- src/include/internal_libreport.h
- src/lib/event_xml_parser.c
- src/report-python/report/dump_dir.c
- src/report-python/report/problem_data.c
- src/report-python/report/reportmodule.c
- src/report-python/report/run_event.c
This adds some missing doc strings in python bindings and fixes a bunch of warnings during compilation.
> Compile warnings

- src/include/internal_libreport.h
- src/lib/dirsize.c
See commits.
Resolves https://github.com/abrt/abrt/issues/1450.  
See also https://github.com/abrt/abrt/pull/1481
> Don't pick .lock'd and new dirs for deletion when problem dirs grow over size limit

- configure.ac
- libreport.spec.in
- src/lib/compress.c
- tests/Makefile.am
- tests/atlocal.in
- tests/bugzilla_plugin.at.in
- tests/local.at
This just undoes some of the damage done over the years to make tests run (or not) in certain situations.
For more, see commits.
Closes https://github.com/abrt/libreport/issues/616
> Make tests great again

- src/gtk-helpers/config_dialog.c
- src/lib/dump_dir.c
- src/lib/get_cmdline.c
- src/lib/make_descr.c
- src/lib/problem_report.c
- src/plugins/rhbz.c
Fixed a couple of issues found by Coverity.
> Fix Coverity defects

- src/gui-wizard-gtk/wizard.c
> wizard: Fix -Wincompatible-pointer-types

- src/lib/get_cmdline.c
- src/plugins/reporter-bugzilla.c
- src/plugins/rhbz.h
> Fix some compile time warnings

- libreport.spec
- libreport.spec.in
While we're at it ...
(https://github.com/abrt/abrt/commit/0debf3a94be7252ae59f7622e8612f6f)
> spec: Drop trailing comment

- CHANGELOG.md
Add https://github.com/abrt/libreport/pull/697 to changelog
> CHANGELOG: Update unreleased

- CHANGELOG.md
- src/gui-wizard-gtk/ignored_words.conf
Related to https://github.com/abrt/abrt/issues/1399.
> ignored_words: add more "key" variations

- src/gtk-helpers/desktop-utils.c
> cli: Add missing g_free call

- src/cli/cli-report.c
- src/lib/run_event.c
Error: CPPCHECK_WARNING (CWE-562): [#def7]
libreport-2.14.0/src/cli/cli-report.c:771: error[autoVariables]: Address of local auto-variable assigned to a function parameter.
> cli: Address of local auto-variable assigned to a function parameter

- src/lib/ureport.c
I do not know why this tmp variable was used this way.
Probably a leftover from some refactoring.
Again this was found by covscan.
> ureport: Strange usage of tmp variable

- src/plugins/python/reporter_bugzilla.py
> reporter_bugzilla.py: Prevent possible KeyError exception

- src/plugins/python/reporter_bugzilla.py
> reporter_bugzilla.py: Fix condition

- CHANGELOG.md
- src/client-python/reportclient/internal/dump_dir.py
- src/client-python/reportclient/internal/problem_formatter.py
- src/plugins/python/reporter_bugzilla.py
> Prevent few possible exceptions

- src/gui-wizard-gtk/ignored_words.conf
Resolves: https://github.com/abrt/libreport/issues/774
> ignored_words: Add KeyboardInterrupt

- libreport.spec
See [the wiki][1] for details.
[1]: https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
> Use SPDX format for license field

- src/client-python/reportclient/internal/bz_connection.py
- src/client-python/reportclient/internal/dump_dir.py
- src/plugins/python/reporter_bugzilla.py
Fixes #786
Fixes rhbz#2176481
Fixes rhbz#2180286
> reporter-bugzilla: Tweaks and fixes

- src/plugins/python/reporter_bugzilla.py
> reporter-bugzilla: Fix string interpolation

- CHANGELOG.md
- src/plugins/reporter-upload.c
> reporter-upload: Fix a use-after-free error in string handling

- libreport.spec
- src/client-python/reportclient/internal/bz_connection.py
- src/gui-wizard-gtk/ignored_words.conf
- src/plugins/python/reporter_bugzilla.py
Multiple small changes that accumulated on my laptop overtime... :)
- add "XDG_ACTIVATION_TOKEN" to the list of ignored words (see the commit message for more details)
- tell Bugzilla that adding a attachment is a minor update so it doesn't send emails
- Fix NameError in reporter-bugzilla
- Retry Bugzilla queries with delays, if needed
> Various fixes

- tests/problem_data.at
- tests/string_list.at
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
> Fix pointer type compatibility issues in tests
