src/gui-wizard-gtk/ignored_words.conf

I am reluctant to use single "accesib" because I am afraid of false
negative results.
Related: rhbz#1175720

gui: ignore (a|A)ccesib(ility|le) words

---

src/gui-wizard-gtk/ignored_words.conf

This was seen in the environment:
SSH_ASKPASS=/usr/libexec/openssh/lxqt-openssh-askpass

ignored words: ignore lxqt-openssh-askpass

---

src/client-python/debuginfo.py
tests/gtk-meh-test.py

This patch just applies what 2to3 found so that the scripts can run both
under python 2 and python 3. More work is needed to fully switch to
python 3.
Related to #172, rhbz#1014684.
Signed-off-by: Martin Milata <mmilata@redhat.com>

Python 3 compatibility

---

libreport.spec.in

plus some magic inside to use dnfdebuginfo.py
Hi, we want to get rid of yum dependency in core f22 image. Then do the new build for f22, please. Thanks.

require dnf instead of yum in f22+

---

src/client-python/reportclient/debuginfo.py

If unpacking of debuginfo fails and '/vat/cache/abrt-di' is not owned by
abrt.abrt the client provides a solution how to fix the issue.
Related to rhbz#1213485

report client: check owner of /var/cache/abrt-di when unpacking fails

---

src/gui-wizard-gtk/wizard.c

There is no icon name `process-close-symbolic`, instead I think you mean `process-stop-symbolic` which does exist.

fix missing icon for "stop" icon name

---

src/plugins/reporter-bugzilla.c

Under some circumstances, it is useful to be able to add
an extra set of ccs to a newly created bug. Add a check for
a file 'extra-cc' which contains e-mails to add to a new
bug.
Signed-off-by: Laura Abbott <labbott@fedoraproject.org>

bugzilla: Add check for extra-cc file

---

src/client-python/reportclient/__init__.py

ldgettext returns an array of bytes in system encoding and this, together with
Python3, causes troubles.

Use a dgettext function returning strings instead of bytes

---

src/gui-wizard-gtk/wizard.c

If the user reviewed the dump dir's files during reporting the crash, the
changes was thrown away and original data was passed to the bugzilla bug
report.
report-gtk saves the first text view buffer and then reloads data from the
reported problem directory, which causes that the changes made to those text
views are thrown away.
This commit fixes the security issue described above.
Related to rhbz#1270235

wizard: fix save users changes after reviewing dump dir files

---

doc/reporter-bugzilla.txt
src/include/dump_dir.h
src/lib/dump_dir.c
src/plugins/reporter-bugzilla.c

reporter-bugzila -h DUPHASH searched duplicate bug only within Fedora products.
This commit makes the feature usable even on RHEL.
Related to rhbz#1268218

reporter-bugzilla: search duplicate bugs within all products

---

doc/Makefile.am
doc/report_Uploader.conf.txt
doc/reporter-upload.txt
doc/upload.conf.txt
libreport.spec.in
src/include/libreport_curl.h
src/lib/curl.c
src/plugins/Makefile.am
src/plugins/report_Uploader.conf
src/plugins/report_Uploader.xml.in
src/plugins/reporter-upload.c
src/plugins/upload.conf

The SSH key files can be set by command line arguments -u (public key) and -r
(private key) or in configuration file upload.conf or in environment variables.
Related to rhbz#1261120

add possibility to configure SSH keys

---

src/lib/dump_dir.c

A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892
https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/
It might improve code understanding, maintainability and error-proneness.

Refactoring conditional directives that break parts of statements.

---

src/plugins/reporter-mailx.c

SELinux does not like mailx creating the file and I do not see any
reason to create the file in a problem directory because the file
contains a copy of the email that could not be send.
Failures of EVENT=notify are discoverable in system logs and if you run
the reporter manually, you will see that mailx failed.

mailx: stop creating dead.letter on mailx failures

---

src/lib/event_xml_parser.c

In a case a file cannot be openned by function
load_event_description_from_file(), no error messages was printed.

xml parser: be more verbose in case xml file cannot be opened

---

doc/reporter-mailx.txt
src/include/internal_libreport.h
src/lib/make_descr.c
src/plugins/reporter-mailx.c

If formatting file is defined, the reporter-mailx
uses problem report api to create content of emails. Section summary is used
for email's subject. If no formatting file is defined, the standart way for
creating email's content is used.
Related to rhbz#1281312

mailx: add posibility to configure email's content

---

src/plugins/reporter-mailx.c

SELinux does not like mailx creating the file and I do not see any
reason to create the file in a problem directory because the file
contains a copy of the email that could not be send.
Failures of EVENT=notify are discoverable in system logs and if you run
the reporter manually, you will see that mailx failed.
Resolves #1309317

RHEL7: mailx: stop creating dead.letter on mailx failures

---

src/lib/create_dump_dir.c
tests/report_python.at

The main purpose of the removed lines in this commit were preventing from
creating non-root dump dir's sub-directrories in the case an uid element
doesn't exist in time of creating the dump dir.
The removed lines are moved to the function problem_data_save() in abrt
src/lib/hooklib.c.
Related to rhbz#1264921

RHEL7: lib: allow report SELinux denial from sealert under common user

---

src/lib/create_dump_dir.c

While journal crashes are extracted we try to read a uid file in time it
doesn't exist. The file is created later within dd_create_basic_files().
Adding DD_FAIL_QUIETLY_ENOENT prevents logging in case the file doesn't exist.

dd: do not log in case the uid file doesn't exist

---

src/include/internal_libreport.h

Fix compile warning for save_user_settings function prototype.

include: save_user_settings function declaration isn’t a prototype

---

src/client-python/reportclient/dnfdebuginfo.py

Internal presetup() used to workaround logging error.
Later introduced warning by API enforcement.
Fixes #438

debuginfo: dnf API logging workarounds list

---

src/plugins/reporter-rhtsupport.c

Introduced in commit 028b35b where I forgot on the code added in commit
5ff7f36.
Related: rhbz#1373094

rhtsupport: fix a double free of config at exit

---

src/plugins/bugzilla_format.conf
src/plugins/bugzilla_format_anaconda.conf
src/plugins/bugzilla_format_analyzer_libreport.conf
src/plugins/bugzilla_formatdup.conf
src/plugins/bugzilla_formatdup_anaconda.conf

The latest version of ABRT generate pkg_vendor and pkg_fingerprint
problem elements in dump directories. These elements have only a little
use in Bugzilla bug description.

bugzilla: stop including package details

---

src/include/internal_libreport.h
src/lib/get_cmdline.c
tests/proc_helpers.at

Compare /proc/[pid]/root to /proc/1/root to ensure that process running
in container will correctly recognize that the tested process is running
on the host.
This would fail with own PID namespace.
Disabling the test because regular users are not allowed to access
/proc/1/root.

lib: correct test for own root

---

src/client-python/reportclient/dnfdebuginfo.py
src/client-python/reportclient/yumdebuginfo.py

ABRT needs to overwrite $releasever when analyzing a problem that
occurred in a container or a changed root environment.

client: add support for $releasever to debuginfo

---

configure.ac
libreport.spec.in

This does not seem to be referenced anywhere.
I might be missing something, but I cannot find where this is used. If it is not needed, can you please merge? If it is still needed, I am sorry for the churn and would like to know what it is used for.

configure.ac: Remove nss dependency

---

src/plugins/reporter-rhtsupport.c

Introduced in commit 028b35b where I forgot on the code added in commit
5ff7f36.
Related: rhbz#1373094

RHEL7: rhtsupport: fix a double free of config at exit

---

autogen.sh

In cases required packages are defined via macro $define and all this
starts with white spaces, list of dependencies contains macro names
instead of the name of packages.

build: fix generating list of dependences in autogen.sh

---

augeas/libreport.aug
augeas/test_libreport.aug

Lens were rewritten to handle whitespaces on EOL and also around value separator.
Tests updated.
Resolves abrt/libreport#474
Related to rhbz#1434414

augeas: trim spaces on eol, around value separator

---

src/plugins/reporter-systemd-journal.c

The PROBLEM_DIR contains path to problem directory.
This features is requested by ABRT cockpit plugin.

reporter-s-journal: add journal entry PROBLEM_DIR

---

src/plugins/reporter-systemd-journal.c

Field count is available only in FULL dump. There are however two good
reasons why to include this in NONE dump.
1. It is quite useful to know if this problem occurred first time or is it
problem that happens a lot.
2. We need it for cockpit integration. If the problem happened more times it
will have multiple logs. By comparing count in the log and real count, we can
know, if this is the last log of the problem. (timestamps do not work ideally
for this, since the time of problem does not equal to the time of the
log - there is some delay)

reporter-s-journal: add count to default logs

---

CHANGELOG.md
src/cli/cli-report.c
src/gui-wizard-gtk/wizard.c
src/include/event_config.h
src/lib/event_config.c
src/report-newt/report-newt.c
tests/event_config.at

Order of login credentials wasn't guaranteed, because event options with missing
values were inserted into hash table and then extracted from it.
I renamed function validate_event as its name was a little bit confusing. The function
returns options that are missing input values and error message should be displayed.
This fixes abrt/abrt#1231

lib: replace hash table with list

---

src/gtk-helpers/autowrapped_label.c
src/gtk-helpers/config_dialog.c
src/gtk-helpers/event_config_dialog.c
src/gtk-helpers/problem_details_widget.c
src/gtk-helpers/workflow_config_dialog.c
src/gui-wizard-gtk/wizard.c

Removing if commands which handled old versions of dtk-3. 
Old version are not used so if commands are not needed.
This one error from issue #488 is still not solved in this work:
event_config_dialog.c:291:9: error: 'gtk_widget_override_color' is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkwidget.h:1144) [-Werror=deprecated-declarations]
gtk_widget_override_color(keyring_warn_lbl, GTK_STATE_FLAG_NORMAL, &red);
^
Created on internship in Redhat.

Deprecated dtk 3 functions

---

src/plugins/reporter-bugzilla.c

The change from commit 946c5 caused that reporter was ALWAYS trying to read
from problem directory. And because the default value for it is set to ".",
running reporter from outside of problem directory caused errors.

bugzilla: add check if option -d was entered

---

libreport.spec.in

Python [23] binary package was renamed to python[23]-libreport
See https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3

spec: rename Python binary packages

---

apidoc/Doxyfile.in

Removes doxygen tags XML_SCHEMA and XML_DTD in apidoc, which became
obsolete and produces warnings while doxygen documentation generation.
Also removes PROJECT_LOGO tag, which caused error because of
non-existing icon image.

doc: fix obsolete doxygen tags & complains

---

libreport.spec.in

We use dnf only in src/client-python/reportclient/dnfdebuginfo.py and it does not call
DNF binary but use python module, which is in pythonX-dnf package

requires pythonX-dnf instead of dnf

---

configure.ac
src/client-python/reportclient/Makefile.am
src/report-python/Makefile.am

This allows python2 and python3 to be independently used for builds that
only require using one or the other.

client-python,report-python: Allow python to be optional at build time

---

doc/reporter-rhtsupport.txt
libreport.spec.in
po/POTFILES.in
src/plugins/Makefile.am
src/plugins/report_RHTSupport_AddData.xml.in
src/plugins/reporter-rhtsupport.c
src/plugins/rhtsupport_event.conf
src/workflows/Makefile.am
src/workflows/report_rhel_add_data.conf
src/workflows/workflow_RHELAddDataCCpp.xml.in
src/workflows/workflow_RHELAddDataJava.xml.in
src/workflows/workflow_RHELAddDataJavaScript.xml.in
src/workflows/workflow_RHELAddDataKerneloops.xml.in
src/workflows/workflow_RHELAddDataLibreport.xml.in
src/workflows/workflow_RHELAddDataPython.xml.in
src/workflows/workflow_RHELAddDatavmcore.xml.in
src/workflows/workflow_RHELAddDataxorg.xml.in
src/workflows/workflow_RHELJavaScript.xml.in

Change behavior of -t parameter in reporter-rhtsupport.
If option -t without support case ID is used and problem data in DIR was never
reported to RHTSupport, you will ask to enter case ID to which you want to
upload the FILEs. If the data in DIR was reported, the case ID is obtained from
'reported_to' element in problem dir. In this case, you will be asked if you
want to attach the data to the support case or you want to change the support
case ID.
Related to #1395285

Add workflow for adding data to existing RH customer case

---

Makefile.am

make release-* commands failed to update changelog in spec when it
contained more than one "changelog" string

makefile: fix make release

---

src/plugins/reporter-bugzilla.c

previous message:
"Please enter your Bugzilla login:"
now:
"Please enter your %s login:"
where %s is configured BugzillaURL, so by default:
"Please enter your https://bugzilla.redhat.com login:"
Related to rhbz#1229439

reporter-bugzilla: ask concrete bz when requiring login

---

libreport.spec.in

Unistalling python{2,3}-libreport, libreport-filesystem leaves behind these directories in the system.
Resolves #514

spec: fix unowned directories

---

src/plugins/mailx.conf
src/plugins/mailx_event.conf
src/plugins/reporter-mailx.c

As a side effect of the fix of rhbz#1093375, the users loosed the control
over their reporter-mailx via configuration file:
/etc/libreport/plugins/mailx.conf
This fix retains this option for the user, but still solves
rhbz#1093375.
Related to rhbz#1523689, rhbz#1093375.

reporter-mailx: rely on configured email

---

src/plugins/reporter-bugzilla.c
src/plugins/reporter-mantisbt.c
src/plugins/reporter-rhtsupport.c

There was an incorrect free of string local_conf right after addition to
the list conf_file, which caused that presence of the pointed string in
the memory was undeterministic. As a result, local config was sometimes
used and sometimes not.

reporter-{bugzilla,mantisbt,rhtsupport}: fix free

---

libreport.spec.in

see https://pagure.io/packaging-committee/issue/736

ldconfig and gtk-update-icon-cache is not needed in rawhide

---

src/lib/ureport.c

This macro has been deprecated and removed from json-c/bits.h.

ureport: remove json-c is_error() usage

---

libreport.spec.in

python-rhsm is obsoleted by subscription-manager-rhsm
Resolves: #1569595

spec: drop dependency on python-rhsm

---

src/plugins/mailx.conf

In 1394000e the default configuration file for reporter-mailx was changed
and it included double quoting the values. However we do not support quoted
values in configuration files and so the the parsed values then included
quotes.

reporter-mailx: Remove double quotes from config

---

po/POTFILES.in
po/POTFILES.skip

src/plugins/report_Bugzilla.xml.in doesn't exist anymore,
it was rename to src/plugins/report_Bugzilla.xml.in.in.
Actualize POTFILES files regarding to this change.
Related to #1449646

potfiles: fix issue in POTFILES.in

---

src/gtk-helpers/problem_details_widget.c

g_type_class_add_private will be deprecated in Glib 2.58 [1].
There is a G_DEFINE_TYPE_WITH_PRIVATE macro that can replace
the deprecated function and it is backwards compatible [2].
[1] https://blog.gtk.org/2018/07/11/news-from-glib-2-58/
[2] https://www.bassi.io/articles/2013/06/21/the-king-is-dead/

gui: Replace deprecated g_type_class_add_private

---

src/gtk-helpers/config_dialog.c

There’s only one column and the model used is not sortable, so it
should just be hidden.
Fixes https://github.com/abrt/gnome-abrt/issues/150

gtk-helpers: config_dialog: Hide tree view header

---

augeas/libreport.aug
augeas/test_libreport.aug

Most of the changes are just replacement of current regexps with in-build modules
from augeas. The changes do not make any major changes in the behaviour of the lenses.
The only thing that is different is that Util.empty [1] module ignores empty comments.
This means that empty commented lines in the configuration files do not show up in
augeas tree and because of that they can't be changed using the augeas.
The goal of this PR is to simplify the augeas lenses but it should also fix the linked
bugzilla bug.
[1] http://augeas.net/docs/references/1.4.0/lenses/files/util-aug.html#Util.empty
Related: rhbz#1649742

augeas: Use generic augeas modules

---

src/gui-wizard-gtk/wizard.c
src/gui-wizard-gtk/wizard.glade
src/lib/event_config.c

Smallest possible window size before:
Smallest possible window size after:
This is sort of a spin-off of https://github.com/abrt/libreport/pull/538, but also redoes the layout a tad, which may or may not be a big no-no, as it is for desktop applications. Additionally, it adds a scrolled window to the entire page, as opposed to the text view only, which would be quite nice with wrapping enabled on the warning labels, but then we still hit the weird underallocation issues and get text overlapping the revealer. Oh, and word-wrapping for lines in the log text view, to avoid infinite horizontal scrolling.

Mix up GTK+ wizard layout a bit

---

src/lib/iso_date_string.c

DST = Daylight Saving Time
Value of this field is not set up by strptime and therefore value
of `tm_isdst` field is undefined. Bacause of this reason, output of
`mktime` may differ +-1 hour.
@mkutlak this should fix tests 26 and 97 on rawhide, can you verify please?

lib: Explicitly do not use DST

---

src/client-python/reportclient/dnfdebuginfo.py
src/lib/event_config.c

The current solution finds packages for given build-ids and then
downloads them. The problem is that some debuginfo packages require
other packages and if they are not available the generated backtrace
becomes unusable.
This commit adds a query for required packages and downloads them together
with the main packages.
And also modify the error message when the backtrace is unusable.
Related: rhbz#1515265

Improve backtrace generation

---

src/plugins/reporter-bugzilla.c
src/plugins/rhbz.c
src/plugins/rhbz.h

In Bugzilla v5.0 nomail flag is replaced with minor_update. [1]
Because we still use the old nomail flag emails are being sent for every added attachment/comment.
Related: rhbz#1660157
Closes: abrt/abrt#1346
See also:
- https://partner-bugzilla.redhat.com/docs/en/html/integrating/api/Bugzilla/WebService/Bug.html?highlight=minor_update
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1655829

rhbz: Replace nomail flag with minor_update

---

src/plugins/rhbz.c

When we are looking for similar bugzillas we only need their IDs. Before
this commit we pulled all information for all bugs, which could cause
that we pulled a lot of data.
Fixes BZ#1660227
Able to reproduce with abrt_hash:6a21339bb55077deb37b421ad0c7601c59a27656

rhbz: Only pull ids when looking for similar bzs

---

libreport.spec.in

References: https://fedoraproject.org/wiki/Changes/RemoveObsoleteScriptlets
(cherry-picked from https://src.fedoraproject.org/rpms/libreport/c/8f048d7d79423a76cfe75dfddd84cbff44164179?branch=master)
Signed-off-by: Igor Gnatenko <ignatenkobrain@fedoraproject.org>

spec: Remove obsolete scriptlets

---

src/plugins/emergencyanalysis_event.conf

See https://bugzilla.redhat.com/show_bug.cgi?id=1540500 and commit messages.
I am more than happy to discuss the message that should be printed. This was my first idea. We need to inform user that when click the URL, is not going to be able to see the archive. The url looks like this: https://retrace.fedoraproject.org/faf/dumpdirs/new/oops-2018-01-26-21:28:20-1347-0.tar.gz/

Enhance emergeny analyses output

---

autogen.sh
tests/Makefile.am
tests/forbidden_words.at
tests/local.at

Was too lazy to split into separate PRs, but here goes.
The test I’m touching is giving me trouble when doing an `rpmbuild -ba`, as the sysconfdir includes the prefix (the spec file does not specify any of the dirs during the invocation of configure), and the expected output is hardcoded.
The changes in autogen.sh are mostly to make things easier when packaging.

autogen.sh tweaks and test “fix”

---

src/lib/problem_report.c

This should make the immediate cause of [#445](https://github.com/abrt/libreport/issues/445) more obvious.
Of course, the reason why the files might be missing from the directories in /var/spool/abrt in the first place is a whole different problem.

Add clearer warnings on missing report elements specified in fmt files

---

src/cli/cli.c

Currently, checking for invalid command line needlessly involves
convoluted bitwise operations, which can be simplified drastically.
First, argc is reduced by optind, which points to the next argument to
be processed. If everything goes well, argc should be 1, since the only
remaining argument to be processed is the problem directory. If that
does not hold, we want to bail. Another point at which we want to bail
is when an option is passed that operates on the positional argument
(anything but -L, which just lists available events). Checking for that
involves ANDing the current option mask with the mask of all such
options. The result is NOTed for comparison, since argc is 0 in such
cases.

cli: Unpack command-line argument parsing logic

---

src/plugins/rhbz.c

It might not be textual, meaning that, if the blob somehow begins with
NUL, it would be treated as empty.

plugins: rhbz: Don’t call strlen() on attachment data

---

configure.ac
src/lib/Makefile.am
src/lib/copy_file_recursive.c

The current recursive copy implementation is rather cumbersome to read
and causes Coverity to complain when building RHEL packages. Using
GLib/GIO should improve readability and eliminate warnings while
retaining compatibility.

lib: copy_file_recursive: Use GLib abstractions

---

src/cli/run-command.c

vfork() replacing fork() was most likely an optimization, but, over
time, changes were added that violate the contract, i.e. the code
started going things other than exec and exit:
https://pubs.opengroup.org/onlinepubs/009695399/functions/vfork.html.
posix_spawn(), as recommended by Clang, would not be a suitable
replacement, as we need to call tcsetpgrp() on the child, doing which
after exec is too late if the goal is to avoid races.

cli: run-command: Replace use of vfork() with fork()

---

src/lib/dirsize.c

With these changes ABRT will skip directories in which sosreport is running
and won't delete them when MaxCrashReportSize limit is exceeded.
I had a concern about the size of the logs that sosreport collects but
there is a limit set by sosreport for how big the individual logs can
be and the default value is 25MiB.
Fixes: rhbz#1671232

dirsize: Skip dirs in which sosreport is being generated

---

src/cli/cli-report.c
src/cli/cli.c
src/gui-wizard-gtk/main.c
src/gui-wizard-gtk/wizard.c
src/include/event_config.h
src/include/run_event.h
src/lib/event_config.c
src/lib/event_xml_parser.c
src/lib/run_event.c
src/lib/workflow.c
src/lib/workflow_xml_parser.c

This proposal repairs the workflow (no pun intended) for workflows that contain event wildcards. The two main changes so far are:
1. Expand wildcards in the workflow XML parser so that the expanded events are available to `report-cli` and `report-gtk` alike. (I'm not happy about doing anything but parsing in the parser, but a more reasonable architecture would likely require significant refactoring.)
2. Don't fail if no matching actions are found for an event. This is a natural thing to happen when using wildcards, since some actions might only make sense for specific problem types.
Fixes #421

Wildcards in event specifications for workflows

---

src/lib/abrt_types.c

Drop warning if a key cannot be found in the supplied configuration map
in the `try_get_map_string_item_as_*` family of functions.
Related: [abrt#1405](https://github.com/abrt/abrt/pull/1405#discussion_r318605702)

lib: Don't warn if a configuration key is missing

---

doc/Makefile.am
doc/bugzilla_formatdup_analyzer_libreport.conf.txt
libreport.spec.in
src/plugins/Makefile.am
src/plugins/bugzilla_event.conf
src/plugins/bugzilla_formatdup_analyzer_libreport.conf

Since we don’t have a duplicate formatting file for libreport-analyzed
problems, reporting things like SELinux AVC denials might result in a
nonexistent file being referenced (e.g. pkg_name, which doesn’t quite
make sense in this case).
Fixes https://github.com/abrt/libreport/issues/445
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1752006

plugins: bugzilla: Add format file for libreport duplicates

---

src/gui-wizard-gtk/main.c
src/gui-wizard-gtk/wizard.c

This misbehaviour seems to have been introduced in 861e8d10b.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1761095

gtk: Fix a double-free condition

---

src/gui-wizard-gtk/wizard.c
src/lib/workflow.c

In light of recently (re)discovered ghastly double-frees, and for very practical reasons as well, I've taken up the task of cleaning up the wizard GUI code. I've started by flushing most of the manual memory management, which seems to be a long-time source of painful problems.
This is but a humble beginning attempting to patch the most glaring holes. There's still a lot left to do to make this into a shiny cathedral.

gtk: Memory management redux

---

src/gui-wizard-gtk/wizard.c

The object should only be freed if we're in the cleanup phase, i.e. only in the if-branch of the condition.
This one was introduced in dc281652.

gtk: Fix another possible double-free

---

maint/pull-translations

`zanata-cli` (from `zanata-platform`) isn't available for Fedora 31+.
We can use `zanata` client that comes from `python3-zanata-client` package.

Update pull-translations script

---

src/gui-wizard-gtk/main.c
src/gui-wizard-gtk/wizard.c
src/gui-wizard-gtk/wizard.h

The expert mode is completely broken and no one seems to be complaining - into the trash it goes.
The ability to user your own UI definitions is completely useless, since:
1. we would normally have to implement changes in a backwards-compatible way,
2. it is ridiculously easy to make everything crash and have the user not realize why,
3. there is no valid use case, just implement a new client if you’re unhappy.

gui-wizard-gtk: Get rid of advanced misfeatures

---

src/include/ureport.h
src/lib/ureport.c
src/plugins/reporter-ureport.c
tests/ureport.at

Currently, it is only possible to attach string and integer data to reports (without formatting a string beforehand), with the latter case simply being a wrapper for the former.
This commit replaces the integer wrapper with a printf-like variadic one should there ever be a need to attach more specific kinds of data.

ureport: Allow printf-like data attaching

---

src/client-python/reportclient/debuginfo.py

A change was introduced in Fedora 27 to allow for installing multiple versions of debuginfo packages in parallel. In effect, `/usr/lib/.build-id` may contain debug files as well in addition to `/usr/lib/debug/.build-id`.
See https://fedoraproject.org/wiki/Changes/ParallelInstallableDebuginfo for more details.
Follow-up to abrt/faf#851.
Corresponding ABRT change: abrt/abrt#1462.

Accomodate for multiple debug directories

---

src/gui-wizard-gtk/wizard.glade

Currently, large logs received by abrt-retrace-client may cause
X/Wayland protocol errors due to an overly large buffer being allocated
for GtkTextView. Enabling word wrapping and eliminating horizontal
scrolling seems to prevent that from happening.
Cf. https://gitlab.gnome.org/GNOME/gtk/issues/1143
https://bugzilla.redhat.com/show_bug.cgi?id=1815544

gui-wizard-gtk: Wrap event log messages

---

src/client-python/reportclient/debuginfo.py

Likely oversight in [commit 324a5ad96572bf6cd384931b0697663dbd00d1c3](https://github.com/abrt/libreport/commit/324a5ad96572bf6cd384931b0697663dbd00d1c3)
that changed the function definition but not the call below in the code

Fix build_ids_to_paths function name

---

configure.ac

expr tested with GNU coreutils and Mac OSX BSD util.
Shell substitution tested with dash.

Use POSIX expr in place of bashisms

---

.git-commit-template

To start using this template:
$ git config commit.template .git-commit-template
If this makes sense, we could add commit templates to other abrt repositories as well.

Add a commit message template

---

src/include/dump_dir.h
src/lib/dump_dir.c
tests/dump_dir.at

Takeover from #570.
Pretty much just rebased on top of master.
Follow-up: abrt/abrt#1484

dd: Update dd_get_owner to handle error return values

---

src/include/event_config.h
src/lib/event_config.c
src/lib/event_xml_parser.c
tests/bugzilla_plugin.at.in

c9120cdc51ce7aba5a19500bf24692144ac64983 in abrt introduced these for
the reporting wizard (advanced mode), but, with that gone, this makes no
sense to keep around.

lib: Remove creates-items tag parsing in event definitions

---

src/include/internal_libreport.h

This `#define` was introduced in fd2f416b3 for no obvious reason and apparently does nothing.

internal: Remove useless #define

---

doc/Makefile.am

There is some more documentation that does not make sense to have
installed when we’re building without the Bugzilla bits.
Fixes https://github.com/abrt/libreport/issues/617

doc: Exclude more files with --without-bugzilla

---

.github/workflows/check.yml

This is to have some kind of public CI job that can be toyed with more
easily by ABRT developers and external contributors alike.

Add GitHub Actions workflow for building PRs

---

src/cli/cli-report.c
src/lib/curl.c
src/lib/steal_directory.c
src/plugins/reporter-mantisbt.c
src/plugins/reporter-systemd-journal.c

The `g_autofree` was incorrectly added in 05e9c9273. This causes a double-free error and crash.
These strings are needed elsewhere and are freed later by `msg_content_free()`.

Fix more memory management errors

---

src/cli/cli-report.c
src/gtk-helpers/problem_details_widget.c
src/gui-wizard-gtk/wizard.c
src/include/internal_libreport.h
src/lib/abrt_xmlrpc.c
src/lib/curl.c
src/lib/glib_support.c
src/lib/libreport-web.sym
src/lib/libreport.sym
src/lib/run_event.c
src/lib/user_settings.c
src/lib/xfuncs.c
src/plugins/mantisbt.c
src/plugins/mantisbt.h
src/plugins/reporter-bugzilla.c
src/plugins/rhbz.c

* Commit 7aba6e5 converted several pointers to GList into `g_autolist`s of `GList`. This is a mistake: the type parameter denotes the type of the contained data, not of the container.
When the `g_autolist`'ed variable goes out of scope, the auto-cleanup procedure attempts to free the data using the `GList` cleanup function, which is `g_list_free()`. This leads to a segfault since the data are usually strings allocated via `malloc()`.
* Replace`libreport_list_free_with_free()` with `g_list_free_full()` everywhere.
* Fix typo in a static function name in `gui-wizard-gtk`.
* Purge commented-out code.
Follow-up in abrt: abrt/abrt#1518

Fix a few segfaults + minor things

---

libreport.spec.in

Per request, to keep SRPMs from koji usable in koschei.
Resolves #661

spec: drop %{?_isa} from BuildRequires

---

libreport.spec.in

`libreport` currently fails to build for ELN.
It also needs to build correctly for ELN. This PR adjusts the SPEC file conditionals to package a Fedora-like reporting onfiguration--even though the `%{rhel}` macro is set. This is different than most other packages which shouldn't care or check if the `%{eln}` macro is set.
This PR corresponds to downstream PR https://src.fedoraproject.org/rpms/libreport/pull-request/4

SPEC file updates for ELN

---

src/cli/cli-report.c
src/include/problem_data.h
src/include/problem_report.h
src/plugins/reporter-bugzilla.c
src/plugins/reporter-kerneloops.c
src/plugins/reporter-mailx.c
src/plugins/reporter-mantisbt.c
src/plugins/reporter-print.c
src/plugins/reporter-systemd-journal.c

* Use `GPtrArray` for pointer arrays in `reporter-mailx`.
* Declare GLib auto-cleanup functions for `problem_data_t`, `problem_formatter_t` and `problem_report_t`.
Broken out of #641.

Memory management and GLib structures

---

src/gui-wizard-gtk/ignored_words.conf

"Bypass" is used in multiple contexts. `IBRS_FW` is used in cpuinfo as indicator of Indirect Branch Restricted Speculation (IBRS), a mitigation technique against Spectre attacks.
Resolves #667

ignored_words: Ignore "bypass" and "IBRS_FW"

---

src/client-python/reportclient/debuginfo.py

Add a new method `get_package_count()` to the `DebugInfoDownload` class which returns the number of packages that will be downloaded.

client-python: Add getter for package count to downloader

---

src/gui-wizard-gtk/main.c
src/gui-wizard-gtk/wizard.c

Since `show_error_as_msgbox()` is specified as the custom logging handler in `gui-wizard-gtk/main.c` (via setting `libreport_g_custom_logger`), it will get called if an error occurs in `libreport_save_user_settings()`. However, at that point, `g_wnd_assistant` has already been destroyed, which leads to an invalid read in `show_error_as_msgbox()`.
This change unsets the custom logging handler after the GUI is destroyed and adds an assertion in `show_error_as_msgbox()` checking that `g_wnd_assistant` is not a null pointer.
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1883337

Fix segfault in gui-wizard-gtk

---

src/lib/event_config.c

The pointers to strings in the function `check_problem_rating_usability()` need to be nullified before the function returns as they are declared for auto-cleanup.
This change fixes a double-free condition in which the returned strings were attempted to be freed again in the caller, `is_backtrace_rating_usable()`.
Bug was introduced in 05e9c9273.
Resolves [rhbz#1883410](https://bugzilla.redhat.com/show_bug.cgi?id=1883410)

Null autofree pointers before returning

---

src/gui-wizard-gtk/wizard.c

`g_object_set_data()` does not (and cannot) copy the data passed to it, so once `url` is freed, a subsequent access to the `url` tag leads to an invalid read and segfault.
Bug was introduced in df386b097.
Resolves [rhbz#1882328](https://bugzilla.redhat.com/show_bug.cgi?id=1882328)

Fix segfault in wizard

---

src/plugins/rhbz.c

The `cc` string must not be freed after the variable goes out of scope since it's appended to `cc_list`. (`g_list_append()` does not copy its input.) We only need to free the last string in the loop, which is an empty string.
The bug was introduced in 7aba6e53.
Resolves [rhbz#1893595](https://bugzilla.redhat.com/show_bug.cgi?id=1893595)

rhbz: Fix a double-free condition

---

libreport.spec.in

This way, when stuff is fixed in automake, the source tarball does not need to be re-generated in upstream to use the fix.
Resolves [rhbz#1893652](https://bugzilla.redhat.com/show_bug.cgi?id=1893652)
Backport of [downstream MR](https://src.fedoraproject.org/rpms/libreport/pull-request/5).

spec: Use autoreconf in %build instead of autoconf

---

README.md

Mention ABRT in the README to put libreport into some context.

README: Reference ABRT in the README

---

libreport.spec
libreport.spec.in

python3-subscription-manager-rhsm isn't required since aeb7980e
Resolves:
https://github.com/abrt/libreport/issues/688

spec: Drop subscription-manager-rhsm dependency

---

src/plugins/reporter-bugzilla.c
src/plugins/reporter-mailx.c
src/plugins/reporter-mantisbt.c
src/plugins/reporter-upload.c
src/plugins/reporter-ureport.c

Strings that are marked for translations should not include macros or any other compile time resolved values.

Untranslatable strings

---

src/gtk-helpers/event_config_dialog.c

Check that the configuration object for the current event is not null. This has been causing segfaults intermittently. I'm not yet sure how exactly this happens so this is kind of a hotfix.
Related: [rhbz#1909855](https://bugzilla.redhat.com/show_bug.cgi?id=1909855)

gtk-helpers: Check for NULL before saving event config data

---

libreport.spec
libreport.spec.in

The support for Red Hat Customer Portal was removed in 1972853. This
forgotten reference in spec file is making the package FTBFS in RHEL now.

[spec] Drop AnacondaRHEL workflow reference

---

configure.ac
libreport.spec
libreport.spec.in
src/lib/Makefile.am
src/lib/dump_dir.c
tests/dump_dir.at

The libtar package is no longer maintained upstream. Besides, we're
already using libarchive elsewhere in the project.  
This commit breaks the corresponding valgrind test (`make maintainer-check-valgrind`) because calling `archive_read_free()` causes a segfault, whereas _not_ calling it causes a leak, obviously. I've tried various ways of closing/freeing the archive_read and archive_entry objects and generally shuffling code around but couldn't find anything that works properly. It's only happening in the test itself so it isn't really an issue. If you feel like digging around in it, I'd love to see what the solution is. I'm probably just being sloppy but I suppose a bug in libarchive isn't out of the question either.
Resolves:
https://bugzilla.redhat.com/show_bug.cgi?id=1917456 …

Replace libtar with libarchive

---

src/client-python/reportclient/__init__.py
src/client-python/reportclient/debuginfo.py
src/client-python/reportclient/dnfdebuginfo.py

* Add typing hints.
* Make code more Pythonic.
* Use `subprocess.run()` instead of `subprocess.Popen`.
* Use sets instead of lists to store packages.
* Fix code style and consistency problems.
* Wrap long lines.
* Various small refactorings.

Refactor reportclient Python library

---

.tito/tito.props

Set tito tag and release title format to simple x.y.z and
Release x.y.z respectively instead of the unwieldy defaults to
continue the release practice used so far.

.tito: Change commit message and tag format

---

CHANGELOG.md
doc/Makefile.am
doc/forbidden_words.conf.txt
doc/ignored_elements.conf.txt
doc/ignored_words.conf.txt
doc/report-gtk.txt
libreport.spec
src/gui-wizard-gtk/Makefile.am
src/gui-wizard-gtk/ignored_elements.conf
src/gui-wizard-gtk/wizard.c

Sections like "cpuinfo" or "open_fds" should be fairly safe
to ignore. There shouldn't be any URLs, tokens or passwords
in them.
Users can still review those sections and custom user searches will still
highlight words in them. We will just not flag any forbidden words in
them by default.
If needed, more sections can be easily added to the list.

Add support for excluding whole elements from search for sensitive words

---

CHANGELOG.md
libreport.spec

Resolves [rhbz#1947018](https://bugzilla.redhat.com/show_bug.cgi?id=1947018)

spec: Make plugin-mailx depend on /usr/bin/mailx

---

.gitignore
libreport.spec

Since the current setup with GitHub Actions automatically opens PRs
against the distgit with each realease tag and since the spec file is
included in the release commit by tito, we want the upstream and distgit
version of the spec file to be as close as possible.

spec: Sync upstream with distgit

---

src/gui-wizard-gtk/wizard.c
src/include/global_configuration.h

Add missing g_strfreev. Reported by covscan. Also
add doxygen comment to the function that allocated
the resources to mention that the returned value
should be freed.

gui-wizard-gtk: Improve docs and add missing free

---

src/gui-wizard-gtk/wizard.c

Hypothetically the g_setenv function can fail. We should
probably not continue execution in that case because users
might accidentally include data in reports that are explicitely
configured not to be included in reports.
Reported by covscan.

gui-wizard-gtk: Check if EXCLUDE_FROM_REPORT is set

---

src/gui-wizard-gtk/wizard.c

g_free does not need to be checked for NULL
but the pointer is not automatically set to NULL
after g_free call.
Found by covscan.

gui-wizard-gtk: Possible double free

---

src/lib/dirsize.c

pPath was checked for NULL after it was already
used in opendir. This would cause Segfault if it
really was NULL.

dirsize: Bad checks for NULL

---

src/lib/dirsize.c

Reported by covscan. If we check for NULL the static
analyzers assume the value can be NULL, but it can not
as it is allocated using the g_* family of functions
and the application would terminate if the memory allocation
failed.

dirsize: No need to check for NULL

---

src/lib/dump_dir.c

We wrongly called free instead of g_free and we
manipulated with already freed pointer without
initializing it back to NULL.
Reported by covscan.

dump_dir: Use g_free instead of free

---

src/lib/dump_dir.c

Covscan reported this as potential double free.
It is definitelly better to re-init to NULL in
case we free memory in the middle of a function
and the pointer is being used after that.

dump_dir: Use g_free and re-init to NULL

---

src/lib/steal_directory.c

This is to silence a double-free warning. The
double-free can not really happen with current code
but it is good practice to init the pointer with
NULL after it is freed and planned to be used
again.

steal_directory: Silence a warning

---

src/gui-wizard-gtk/wizard.c
src/lib/run_event.c

A double free seems to have been introduced in 7342f26c.
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1965633

Fix segfault/double-free

---

configure.ac
src/lib/curl.c
src/lib/proxies.c

GProxyResolver has been around since GLib 2.26. There's no reason to use
libproxy directly anymore. GProxyResolver will call into libproxy if
GLib thinks it's a good idea to do so, except in distributions that are
configured to build glib-networking without libproxy support.
Note that the existing code in get_proxy_list() was unsafely using
g_autofree and g_free() to free the memory allocated by libproxy. With
the switch to GProxyResolver, the memory is actually allocated by GLib
now, so this is now actually correct to do.
**Note that this commit is untested.** I just checked to make sure that it builds. **It will probably work, but please sanity-check to ensure it doesn't crash at runtime before merging.** The APIs are basically 1:1 except for some details around SOCKS proxies that …

Avoid direct use of libproxy

---

libreport-web.pc.in
libreport.spec

Dependency on libproxy was factually removed in 11df7ffc. This change follows up by removing the formal dependency in the spec and pkgconfig files.

spec: Drop libproxy dependency

---

CHANGELOG.md
src/plugins/rhbz.c

Most of the components in Bugzilla don't have any subcomponents, so we need to be careful when handling them.

reporter-bugzilla: fix subcomponent handling for RHEL

---

CHANGELOG.md
src/lib/abrt_xmlrpc.c
src/lib/abrt_xmlrpc.h
src/lib/libreport-web.sym
src/plugins/rhbz.c

If there is a bot that automatically modifies newly opened bugs, then
it can lead to "query serialization error" from Bugzilla. Retry should
help us here.

[rhbz] Retry XML-RPC calls when uploading attachments

---

tests/client_python.at

unittest.assertEquals was deprecated in Python 3.2 and will no longer be
supported in 3.11
Resolves:
https://bugzilla.redhat.com/show_bug.cgi?id=2019402

tests: Don't use deprecated assertEquals

---

src/plugins/reporter-bugzilla.c
src/plugins/reporter-upload.c
src/plugins/rhbz.c
src/report-python/report/__init__.py

According to a comment in the code, we should be ignoring this file since a long time ago. We never create it anymore and these were the only instances left in code referencing it.
+ Various marginal code style clean ups.

Drop last references to global_uuid file

---

src/plugins/reporter-bugzilla.c

Make the APIKey config key consistent in bugzilla.conf and
reporter-bugzilla cmdline help  
(Such a silly nitpick but I'm working on this ATM and got confused :))

reporter-bugzilla: Fix APIKey name

---

CHANGELOG.md
src/lib/Makefile.am
src/lib/abrt_xmlrpc.c
src/lib/abrt_xmlrpc.h
src/lib/libreport-web.sym
src/plugins/reporter-bugzilla.c

But only if the target instance is Red Hat Bugzilla.
This change is required as Red Hat Bugzilla expects the API key
to be in the HTTP header and it won't find it in XML-RPC params.
xmlrpc-c doesn't support custom headers. Only User-Agent header
is supported. However, since HTTP is a text protocol, we can add
more headers by simply strategically placing line break characters
("\r\n" for HTTP) inside the User-Agent header.
HTTP will do the right thing and interpret such string as multiple
headers.

reporter-bugzilla: send API key in HTTP header

---

src/lib/abrt_xmlrpc.c

See commit. Just a warning I keep running into

abrt_xmlrpc: Don't warn about discarded const

---

src/plugins/python/reporter_bugzilla.py

set_settings() populates "rhbz" dict with settings from both config files and environment variables. gnome-abrt passes the API key to reporter-bugzilla via "Bugzilla_APIKey" env. variable.

reporter_bugzilla.py: Don't ask for API key if we already have it

---

README.md

Use the native Mermaid.js integration in GitHub Markdown to display a clickable diagram of related repositories, i.e. the relevant repos in the abrt organization.

readme: Add diagram of related projects

---

src/client-python/reportclient/internal/const.py
src/include/internal_libreport.h
src/plugins/python/reporter_bugzilla.py
src/plugins/reporter-bugzilla.c
src/plugins/reporter-mantisbt.c

Honor XDG_CONFIG_HOME variable if set, to access user's local configuration file, and fixes reporter_bugzilla.py's user local path computation.
For C code, Glib's g_get_user_config_dir() deals with XDG_CONFIG_HOME transparently for us.
For Python, external dependencies such as pyxdg, xdg-base-dirs, or appdirs could have been used to achieve the same behavior as Glib's g_get_user_config_dir(), but the choice to not depends on external packages was made.
Fixes #782.

use $XDG_CONFIG_HOME to access user's configuration files (fix #782)

---

CHANGELOG.md
src/gui-wizard-gtk/wizard.glade

Enable word wrap in GTK report wizard to avoid the need of horizontal scrolling

GTK report wizard: Enable word wrap

---

src/plugins/mantisbt.h

Since libxml2 2.12, `xmlNodePtr` is no longer included by `libxml/encoding.h`. This leads to build errors such as:
CC       reporter_mantisbt-reporter-mantisbt.o
In file included from reporter-mantisbt.c:22:
mantisbt.h:48:5: error: unknown type name ‘xmlNodePtr’
48 |     xmlNodePtr sr_root;
|     ^~~~~~~~~~
mantisbt.h:49:5: error: unknown type name ‘xmlNodePtr’
49 |     xmlNodePtr sr_body;
|     ^~~~~~~~~~
mantisbt.h:50:5: error: unknown type name ‘xmlNodePtr’
50 |     xmlNodePtr sr_method;
|     ^~~~~~~~~~
Fix this by including `libxml/tree.h`.

Fix compatibility with libxml2 2.12
